# Generated by Django 4.2.28 on 2026-05-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('key', models.SlugField(help_text='Example: store_name, primary_color', max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('textarea', 'Textarea'), ('select', 'Select'), ('toggle', 'Toggle'), ('file', 'File'), ('color', 'Color'), ('password', 'Password')], max_length=30)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('default_value', models.TextField(blank=True)),
                ('value', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, help_text='For select field only. Example: [{"label":"India","value":"IN"}]', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Setting Field',
                'verbose_name_plural': 'Setting Fields',
                'ordering': ['group__level__order', 'group__order', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SettingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(blank=True, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Setting Level',
                'verbose_name_plural': 'Setting Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(blank=True, null=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Example: fa-solid fa-gear / bi bi-gear / settings', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='site_settings.settinglevel')),
            ],
            options={
                'verbose_name': 'Setting Group',
                'verbose_name_plural': 'Setting Groups',
                'ordering': ['level__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SettingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='site_settings/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(limit_choices_to={'field_type': 'file'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file', to='site_settings.settingfield')),
            ],
            options={
                'verbose_name': 'Setting File',
                'verbose_name_plural': 'Setting Files',
            },
        ),
        migrations.AddField(
            model_name='settingfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='site_settings.settinggroup'),
        ),
        migrations.AddConstraint(
            model_name='settingfield',
            constraint=models.UniqueConstraint(fields=('group', 'key'), name='unique_setting_field_key_per_group'),
        ),
    ]
