"""
Django settings for vastrika_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# --------------- setup --------------- #
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# -------------- BASE DIR --------------- #
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"

# ------------- SECURITY -------------- #
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-s=kizn7iu-@a4b#jt1m!4d&zji($6b8pcylim%(j8$fr2=07e*'
# SECRET_KEY = os.environ.get('SECRET_KEY')
# SECRET_KEY = "django-insecure-change-this-in-production"
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True # Production
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Application definition - INSTALLED APPS
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # -----Third-party other apps ----- #
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",

    # ----- Django Apps ----- #
    "apps.accounts", # It must include the 'apps.' prefix
    "apps.products",
    "apps.orders",
    "apps.customers",
    "apps.reports",
    "apps.site_settings",
    "apps.core.apps.CoreConfig",
    "channels",
    "django_filters",
    "apps.reviews",
]

ASGI_APPLICATION = "vastrika_backend.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
    }
}

# ---------- MIDDLEWARE ---------- #
MIDDLEWARE = [
    # ----- other middleware ----- #
    "corsheaders.middleware.CorsMiddleware", # must be at top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    # CSRF (important for cookies)
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # ----- Django MIDDLEWARE ----- #
    "apps.core.audit_middleware.AuditUserMiddleware",
]

# ---------- URL ---------- #
ROOT_URLCONF = "vastrika_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vastrika_backend.wsgi.application"

# --------- DATABASE --------- #
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "vastrika_ecommerce", # use the exact database name you created in phpMyadmin
        "USER": "root", # Default XAMPP user
        "PASSWORD": "", # Defalult XAMPP password is empty
        "HOST": "127.0.0.1",
        "PORT": "3306", # Default MySQL port
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# --------- PASSWORD VALIDATION ---------- #
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # { "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", },
    { "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
      "OPTIONS": {"min_length": 8},
    },
    { "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    { "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# --------- INTERNATIONAL ---------- #
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True

# --------- STATIC ---------- #
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------- COOKIE SETTINGS (VERY IMPORTANT) ---------- #
# JWT_AUTH_COOKIE = 'access_token'

# -------- CUSTOM LOGIN USER --------- #
AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    # "apps.accounts.authentication.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# ---------- REST FRAMEWORK --------- #
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

# ---------- JWT SETTINGS ---------- #
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # 'AUTH_COOKIE': 'access_token',
    # 'AUTH_COOKIE_SECURE': False,
    # 'AUTH_COOKIE_HTTP_ONLY': True,
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),

    # Important for custom user
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# ---------- CORS SETTINGS ---------- #
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # using (vite) frontend
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True # Allow React Frontend

# ---------- CSRF SETTINGS (IMPORTANT) ---------- #
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

APPEND_SLASH = True

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_VERIFY_SERVICE_SID = os.getenv("TWILIO_VERIFY_SERVICE_SID", "")