# Generated by Django 4.2.28 on 2026-05-30 05:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number contains invalid characters.', regex='^[0-9+\\-\\s()]+$')])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='customers_c_created_1ed0f4_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'), models.Index(fields=['is_verified'], name='customers_c_is_veri_2aa730_idx')],
            },
        ),
    ]
