# Generated by Django 4.2.28 on 2026-05-30 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Customer Report',
                'verbose_name_plural': 'Customer Reports',
                'db_table': 'reports_customer_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product Report',
                'verbose_name_plural': 'Product Reports',
                'db_table': 'reports_product_report',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'db_table': 'reports_sales_report',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='reports_sal_report__b4501a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_sales__gte', 0)), name='sales_report_total_sales_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_orders__gte', 0)), name='sales_report_total_orders_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_customers__gte', 0)), name='sales_report_total_customers_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.UniqueConstraint(fields=('report_date',), name='unique_sales_report_per_day'),
        ),
        migrations.AddField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_reports', to='products.product'),
        ),
        migrations.AddField(
            model_name='customerreport',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productreport',
            index=models.Index(fields=['product', 'report_date'], name='reports_pro_product_ba4267_idx'),
        ),
        migrations.AddIndex(
            model_name='productreport',
            index=models.Index(fields=['report_date'], name='reports_pro_report__2fb5a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.CheckConstraint(check=models.Q(('total_sales__gte', 0)), name='product_report_total_sales_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.CheckConstraint(check=models.Q(('total_quantity__gte', 0)), name='product_report_total_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.UniqueConstraint(fields=('product', 'report_date'), name='unique_product_report_per_day'),
        ),
        migrations.AddIndex(
            model_name='customerreport',
            index=models.Index(fields=['customer', 'report_date'], name='reports_cus_custome_71f707_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreport',
            index=models.Index(fields=['report_date'], name='reports_cus_report__0d3bac_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.CheckConstraint(check=models.Q(('total_orders__gte', 0)), name='customer_report_total_orders_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.CheckConstraint(check=models.Q(('total_spent__gte', 0)), name='customer_report_total_spent_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.UniqueConstraint(fields=('customer', 'report_date'), name='unique_customer_report_per_day'),
        ),
    ]
