# Generated by Django 4.2.28 on 2026-05-09 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['report_date'], name='reports_sal_report__92f498_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Report',
                'verbose_name_plural': 'Customer Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Report',
                'verbose_name_plural': 'Product Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['product', 'report_date'], name='reports_pro_product_aac171_idx'), models.Index(fields=['report_date'], name='reports_pro_report__a747c7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.UniqueConstraint(fields=('product', 'report_date'), name='unique_product_report_per_day'),
        ),
        migrations.AddIndex(
            model_name='customerreport',
            index=models.Index(fields=['customer', 'report_date'], name='reports_cus_custome_bff9da_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreport',
            index=models.Index(fields=['report_date'], name='reports_cus_report__65b5c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.UniqueConstraint(fields=('customer', 'report_date'), name='unique_customer_report_per_day'),
        ),
    ]
