# Generated by Django 4.2.28 on 2026-05-19 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerreport',
            new_name='reports_cus_custome_71f707_idx',
            old_name='reports_cus_custome_bff9da_idx',
        ),
        migrations.RenameIndex(
            model_name='customerreport',
            new_name='reports_cus_report__0d3bac_idx',
            old_name='reports_cus_report__65b5c5_idx',
        ),
        migrations.RenameIndex(
            model_name='productreport',
            new_name='reports_pro_product_ba4267_idx',
            old_name='reports_pro_product_aac171_idx',
        ),
        migrations.RenameIndex(
            model_name='productreport',
            new_name='reports_pro_report__2fb5a2_idx',
            old_name='reports_pro_report__a747c7_idx',
        ),
        migrations.RenameIndex(
            model_name='salesreport',
            new_name='reports_sal_report__b4501a_idx',
            old_name='reports_sal_report__92f498_idx',
        ),
        migrations.AlterField(
            model_name='customerreport',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerreport',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_reports', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='report_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.CheckConstraint(check=models.Q(('total_orders__gte', 0)), name='customer_report_total_orders_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customerreport',
            constraint=models.CheckConstraint(check=models.Q(('total_spent__gte', 0)), name='customer_report_total_spent_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.CheckConstraint(check=models.Q(('total_sales__gte', 0)), name='product_report_total_sales_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productreport',
            constraint=models.CheckConstraint(check=models.Q(('total_quantity__gte', 0)), name='product_report_total_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_sales__gte', 0)), name='sales_report_total_sales_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_orders__gte', 0)), name='sales_report_total_orders_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.CheckConstraint(check=models.Q(('total_customers__gte', 0)), name='sales_report_total_customers_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='salesreport',
            constraint=models.UniqueConstraint(fields=('report_date',), name='unique_sales_report_per_day'),
        ),
        migrations.AlterModelTable(
            name='customerreport',
            table='reports_customer_report',
        ),
        migrations.AlterModelTable(
            name='productreport',
            table='reports_product_report',
        ),
        migrations.AlterModelTable(
            name='salesreport',
            table='reports_sales_report',
        ),
    ]
