# Generated by Django 4.2.28 on 2026-05-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='products.brand'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='parent_categories', to='products.producttag'),
        ),
    ]
