# Generated by Django 4.2.28 on 2026-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_parentcategory_brands_parentcategory_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
