# Generated by Django 4.2.28 on 2026-05-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_low_stock_threshold_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
