# Generated by Django 4.2.28 on 2026-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
