# Generated by Django 4.2.28 on 2026-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_subcategory_meta_description_subcategory_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
