# Generated by Django 4.2.28 on 2026-05-26 13:14

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_delivery_time_product_free_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_brand_name_lower'),
        ),
    ]
