# Generated by Django 4.2.28 on 2026-05-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_brand_name_brand_unique_brand_name_lower'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brand',
            name='unique_brand_name_lower',
        ),
    ]
