# Generated by Django 4.2.28 on 2026-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_tax_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_class',
            field=models.CharField(choices=[('gst_0', 'GST 0%'), ('gst_5', 'GST 5%'), ('gst_12', 'GST 12%'), ('gst_18', 'GST 18%'), ('gst_28', 'GST 28%')], default='gst_0', max_length=20),
        ),
    ]
