# Generated by Django 4.2.28 on 2026-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brand_meta_description_brand_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False),
        ),
    ]
