# Generated by Django 4.2.28 on 2026-06-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_tax_class'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='products_selling_price_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_mrp_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_selling_price_lte_mrp',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_avg_rating_between_0_5',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_feat_a5d7cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_new__3974ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_best_e07ac4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_gender_b0135f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_parent__ecf896_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sub_cat_f10c11_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_child_c_07da80_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_selling_77a2d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_created_52f0d7_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_backorders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='free_shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_best_seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_cod_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_exchangeable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_returnable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wishlist_count',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('gst_0', 'GST 0%'), ('gst_5', 'GST 5%'), ('gst_12', 'GST 12%'), ('gst_18', 'GST 18%'), ('gst_28', 'GST 28%')], default='gst_0', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
