# Generated by Django 4.2.28 on 2026-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_products_selling_price_gte_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='review_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
