# Generated by Django 4.2.28 on 2026-06-07 17:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariant_review_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(choices=[('1-2_days', '1-2 Days'), ('3-5_days', '3-5 Days'), ('5-7_days', '5-7 Days')], default='3-5_days', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_exchangeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('sports', 'Sports'), ('festive', 'Festive'), ('ethnic', 'Ethnic'), ('lounge', 'Lounge')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('fragile', 'Fragile')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new_arrival'], name='products_pr_is_new__3974ad_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_seller'], name='products_pr_is_best_e07ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender'], name='products_pr_gender_b0135f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['parent_category'], name='products_pr_parent__ecf896_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category'], name='products_pr_sub_cat_f10c11_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['child_category'], name='products_pr_child_c_07da80_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['selling_price'], name='products_pr_selling_77a2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__gte', 0)), name='products_selling_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('mrp__gte', 0)), name='products_mrp_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__lte', models.F('mrp'))), name='products_selling_price_lte_mrp'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='products_avg_rating_between_0_5'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
