# Generated by Django 4.2.28 on 2026-06-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_parent__ecf896_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sub_cat_f10c11_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
