# Generated by Django 4.2.28 on 2026-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_products_pr_parent__ecf896_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this warehouse for inventory operations.'),
        ),
    ]
