# Generated by Django 4.2.28 on 2026-06-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_warehouse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload product demonstration video.', null=True, upload_to='products/videos/'),
        ),
    ]
