# Generated by Django 4.2.28 on 2026-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productimage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload MP4, WEBM or MOV video.', null=True, upload_to='products/videos/'),
        ),
    ]
