# Generated by Django 4.2.28 on 2026-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_productimage_video_product_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id']},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('gallery', 'Gallery'), ('zoom', 'Zoom')], default='gallery', max_length=20),
        ),
    ]
