# Generated by Django 4.2.28 on 2026-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productimage_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/seo/'),
        ),
    ]
