# Generated by Django 4.2.28 on 2026-06-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='delivery_coverage_area',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fulfillment_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipping_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
