# Generated by Django 4.2.28 on 2026-06-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_warehouse_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('daily-wear', 'Daily Wear'), ('office-wear', 'Office Wear'), ('formal', 'Formal'), ('business', 'Business'), ('party-wear', 'Party Wear'), ('wedding', 'Wedding'), ('lounge', 'Lounge'), ('festive', 'Festive'), ('sports', 'Sports'), ('running', 'Running'), ('training', 'Training'), ('gym', 'Gym'), ('walking', 'Walking'), ('travel', 'Travel'), ('outdoor', 'Outdoor'), ('adventure', 'Adventure'), ('hiking', 'Hiking'), ('trekking', 'Trekking'), ('camping', 'Camping'), ('school', 'School'), ('college', 'College'), ('weekend', 'Weekend'), ('beach', 'Beach'), ('vacation', 'Vacation'), ('driving', 'Driving'), ('winter-wear', 'Winter Wear'), ('rainy-season', 'Rainy Season'), ('premium-collection', 'Premium Collection'), ('luxury-events', 'Luxury Events'), ('athleisure', 'Athleisure'), ('streetwear', 'Streetwear'), ('ethnic', 'Ethnic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('lightweight-footwear', 'Lightweight Footwear'), ('standard-footwear', 'Standard Footwear'), ('premium-footwear', 'Premium Footwear'), ('outdoor-footwear', 'Outdoor Footwear'), ('heavy-duty-footwear', 'Heavy Duty Footwear'), ('express-shipping', 'Express Shipping'), ('standard-shipping', 'Standard Shipping'), ('free-shipping', 'Free Shipping'), ('international-shipping', 'International Shipping')], default='standard', max_length=50),
        ),
    ]
