# Generated by Django 4.2.28 on 2026-06-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_occasion_alter_product_shipping_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_class',
            field=models.CharField(choices=[('lightweight-footwear', 'Lightweight Footwear'), ('standard-footwear', 'Standard Footwear'), ('premium-footwear', 'Premium Footwear'), ('outdoor-footwear', 'Outdoor Footwear'), ('heavy-duty-footwear', 'Heavy Duty Footwear'), ('express-shipping', 'Express Shipping'), ('standard-shipping', 'Standard Shipping'), ('free-shipping', 'Free Shipping'), ('international-shipping', 'International Shipping'), ('lifestyle-footwear', 'Lifestyle Footwear')], default='standard', max_length=50),
        ),
    ]
