# Generated by Django 4.2.28 on 2026-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_shipping_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Display name for this variant.', max_length=255),
        ),
    ]
