# Generated by Django 4.2.28 on 2026-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='damaged_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Damaged units not available for sale.'),
        ),
    ]
