# Generated by Django 4.2.28 on 2026-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_productvariant_damaged_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Height in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Length in cm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kg', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Width in cm', max_digits=10),
        ),
    ]
