# Generated by Django 4.2.28 on 2026-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_height_alter_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='wishlist_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
