# Generated by Django 4.2.28 on 2026-06-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_productimage_review_count_productimage_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='wishlist_count',
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
